services:
  - type: web
    name: fer-proj-api
    env: python
    plan: free
    region: oregon

    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        cmake \
        git \
        wget \
        libgl1 \
        libglib2.0-0 && \
      pip install --upgrade pip && \
      pip install --no-cache-dir -r requirements.txt

    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
